### ISSUE TITLE
Game freezes when exiting the ship log in map mode

### ISSUE THREAD

**Issue by floatieforreal** [dgarroDC/ShipLogSlideReelPlayer#1]
When I enter the ship log in map mode and immediately exit without looking at any of the entries, the game freezes.

I'm on game version 1.1.12.125.

The mod manager also gives me this error:

NullReferenceException: Object reference not set to an instance of an object Stacktrace: ShipLogSlideReelPlayer.ShipLogSlideReelPlayer.UnloadStreamingTextures (ShipLogMapMode mapMode, System.Int32 index, System.Collections.Generic.List`1[T] wantedStreamingAssetIDs) (at <a71182ec89ba49459916131a62134ffc>:0) ShipLogSlideReelPlayer.ShipLogSlideReelPlayer.CloseEntryMenu (ShipLogMapMode __instance) (at <a71182ec89ba49459916131a62134ffc>:0) (wrapper dynamic-method) ShipLogMapMode.DMD<ShipLogMapMode::CloseEntryMenu>(ShipLogMapMode) ShipLogMapMode.ExitMode () (at <6981773f82a4486a9b48d7b04937b6e2>:0) ShipLogController.ExitShipComputer () (at <6981773f82a4486a9b48d7b04937b6e2>:0) ShipLogController.Update () (at <6981773f82a4486a9b48d7b04937b6e2>:0)

**Comment by dgarroDC** [comment]
Thank you @ZAFloatie for reporting this important bug and giving all the details! This is now fixed in 1.0.5, you can update now in the mod manager :)
