### ISSUE TITLE
Make the thumbnail less spoilery?

### ISSUE THREAD

**Issue by Raicuparta** [dgarroDC/ShipLogSlideReelPlayer#2]
Any chance you could change the thumbnail so it doesn't spoil anything for people who haven't played the dlc? You can just blur the face or use a different, more vague-looking slide.

Having spoilers on the readme body is ok, but just the first image should be clean of spoilers.

**Comment by dgarroDC** [comment]
Removed in 959ad96b64d98907687187cdf4086b381450a773, will make a proper one later
