### ISSUE TITLE
duplicate logs on leaving and reentering ship log

### ISSUE THREAD

**Issue by XertroV** [dgarroDC/ShipLogSlideReelPlayer#4]
Had a bug last night where leaving and reentering the ship log (or maybe just entries for the stranger) would duplicate the slide reel entries. Illustrative examples:

first viewing:
```
- A
  - reel 1
- B
  - reel 2
  - reel 3
```

second viewing:
```
- A
  - reel 1
  - reel 1
- B
  - reel 2
  - reel 3
  - reel 2
  - reel 3
```

(note the order of reels 2/3 under B)

I think it should be easy to replicate, but LMK if not and I'll try to come up with a way to replicate.

I *think* it resets back to normal each loop.

**Comment by dgarroDC** [comment]
Thank you for the report! I probably introduced this bug in the last update, I will fix it asap
